baseurl: 'https://carsonslater.com/'
languageCode: en-US
title: Carson L. Slater
theme: hugo-profile
googleAnalytics: 'G-24B431J36B'
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
# menu:
#   main:
#     - name: About
#       url: /about/
#     - name: GitHub
#       url: https://github.com/rstudio/blogdown
#     - name: Twitter
#       url: https://twitter.com/rstudio
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: blogs
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/icon2.png"
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  # logo:
  #  alt: Logo
  #  height: 50
  #  url: logo.png
  #  width: 50

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: "#192C4E"
    secondaryTextColor: "#192C4E"
  #   backgroundColor:
    secondaryBackgroundColor: "#192C4E"
    primaryColor: "#FF6600"
  #   secondaryColor: 

    darkmode:
  #     textColor: 
  #     secondaryTextColor:
      backgroundColor: "#192C4E"
  #    secondaryBackgroundColor: "#B7ABA8"
      primaryColor: "#FF6600"
      secondaryColor: "#192C4E"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Carson Slater" # Brand name for the brand | default is the title variable
    disableSearch: true
    searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Howdy, my name is"
    title: "Carson."
    subtitle: "I uncover stories using statistical methods."
    content: ""
    image: /static/icon2.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Vita"
      url: "resume.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/carsonslater
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/carsonslateratbaylor/
        - icon: fab fa-instagram
          url: https://www.instagram.com/slatercarson/

  # About
  about:
    enable: true
    title: "About Me"
    image: "images/avatar4.png"
    content: |-
      I am a first-year graduate student in the <a href="https://statistics.artsandsciences.baylor.edu"> Department of Statistical Science </a> at <a href = "https://www.baylor.edu"> Baylor University </a>. I moved to Waco after completing my undergraduate studies at <a href = "https://www.wheaton.edu"> Wheaton College </a>, where I played baseball for the Thunder. I proudly hail from Phoenix and will spend every second I can visiting northern Arizona. 
      
      Generally speaking, you can find me at <a href = "https://gracewaco.com"> Grace Church Waco </a> on a given Sunday morning, and I'm always trying to find a way to go back to the Czech Republic to work with <a href = "https://kam.cz"> Křesťanská Akademie Mladých </a> again.
      
      Currently, I am learning many new statistical methods that will enable me to build predictive models, understand stochastic phenomena, and discover associations in our world.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "R/RStudio"
        - "Quarto"
        - "reveal.js"
        - "Git/Github"
        - "Docker"
        - "LaTeX"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Graduate Assistant"
        company: "Baylor University"
        companyUrl: "https://www.baylor.edu"
        date: "Aug 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: I am currently one of the youngest people in the graduate school at Baylor.
        content: "I am currently working as a graduate supplemental instructor for the Introduction to Statistical Methods course (STA 2381) at Baylor University."
      
      
      - job: "Intern"
        company: "KAM"
        companyUrl: "https://kam.cz"
        date: "June 2023 - Aug 2023"
        info:
          enable: true
          content: KAM-CZ is a national organization that functions as a subset of a larger organization called Josiah Venture.
        featuredLink:
          enable: true
          url: "https://www.youtube.com/watch?v=9g9W-Tql_Cs"
        content: "After support raising for four months, I spent two and a half months working for a youth missions organization in Central and Eastern Europe, called KAM (Křesťanská Akademie Mladých). For this work I lived in Ostrava, CZ where I assisted local CB churches with youth outreach through camps where I taught English and sports. I also helped onboard short-term mission teams who joined us for camps."
        
      - job: "Academic Coach"
        company: "Wheaton Academy"
        companyUrl: "https://wheatonacademy.org"
        date: "Jan 2023 - May 2023"
        featuredLink:
          enable: false
          url: "https://example.com"
        # info:
        #   enable: false
        #   content: I worked as a software developer for more than one year in Amazon.
        content: "In this role I met with students 1-on-1 per their request to teach, review, and sharpen their math skills. I met with students ranging in courses from Algebra I to AP Statistics to help them prepare for their exams, whether it’s ones for courses or AP exams."

      - job: "Teaching Assistant"
        company: "Wheaton College"
        companyUrl: "https://www.wheaton.edu/academics/departments/mathematics/"
        date: "Aug 2022 - May 2023"
        # info:
        #   enable: false
        # featuredLink:
        #   enable: false
        #   url: "https://example.com"
        content: |
          I was the teaching assistant for <a href = "https://peter-jantsch.github.io"> Dr. Peter Jantsch </a> in the fall of 2022 and spring of 2023. I hosted weekly help sessions for students to come in for extra help, and graded course homework. The courses I helped with were:

          - MATH 465: Applied Machine Learning,
          - MATH 363: Probability Theory.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "M.S. Statistics"
        school:
          name: "Baylor University"
          url: "https://www.baylor.edu"
        date: "Pending"
        GPA: "3.90 out of 4.00"
        content: |-
          Extracurricular Activities
            - Baylor Sports Analytics Club
            - Baylor Country Dance Club
      - title: "B.S. Applied Mathematics,   B.A. Economics"
        school:
          name: "Wheaton College (IL)"
          url: "https://www.wheaton.edu"
        date: "2019 - 2023"
        GPA: "3.46 out of 4.00"
        content: |-
          Extracurricular Activities
            - Varsity Baseball
            - 2020-2021 Sophomore Class Council
  # # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #       image: /images/achievment.jpg
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #       image: /images/achievment.jpg
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Assessing Aggregate Interference with Regression Analysis Techniques
        content: Using GAMs to predict interference in Dynamic Spectrum Access.
        image: /images/projects/noise_pred.png
        featured:
          name: Paper
          link: "/regression_agg_interference_final.pdf"
        badges:
          - "Dynamic Spectrum Access"
          - "Generalized Additive Models"
          - "R/RStudio"
          - "ggplot2"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Assessing%20Aggregate%20Interference%20Using%20GAMs&body=Check%20out%20this%20project:%20https%3a%2f%2fcarsonslater.com%2f
          - icon: fab fa-github
            url: https://github.com/carsonslater/Predicting_Aggregate_Interference

      # - title: Image Converter
      #   content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
      #   image: /images/projects/converter.jpg
      #   featured:
      #     name: Demo
      #     link: https://django-converter.herokuapp.com
      #   badges:
      #     - "Django"
      #     - "Bootstrap"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/converter
      # 
      # - title: Hugo Profile V2
      #   content: A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: carson_slater1@baylor.edu
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: /blogs
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/carsonslater
      linkedin: https://www.linkedin.com/in/carsonslateratbaylor/
      instagram: https://www.instagram.com/slatercarson/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Carson Slater, All Rights Reserved."
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
